name:                haskupcake
version:             0.1.0.0
github:              "mikaunix/haskupcake"
license:             GPL-3
author:              "Mikaël Dusenne"
maintainer:          "mikaeldusenne@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mikaunix/haskupcake#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - http-client
    - http-client-tls
    - bytestring
    - conduit
    - resourcet
    - http-client
    - http-types
    - conduit-extra
    - aeson
    - unordered-containers
    - vector
    - filepath
    - case-insensitive
    - aeson-pretty
    - text
    - uri-encode
    - directory
    - mtl
    - transformers
    - scientific
    - time
    - MissingH
    - parsec
    - monadplus

executables:
  haskupcake:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskupcake
    - bytestring
    - aeson-pretty
    - unordered-containers
    - transformers    

tests:
  haskupcake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskupcake
    - hspec
    - bytestring
